config/routes.rb
Rails.application.routes.draw do
  
  resources :projects do
    resources :tasks, only: [:create, :destroy]
  end

  post '/projects/:project_id/tasks/:id/toggle' => 'tasks#toggle'

  get 'projects/index'

  get 'projects/new'

  get 'projects/show'

  get 'projects/create'

  get 'projects/edit'

  get 'projects/update'

  get 'projects/destroy'

  authenticated :user do
    get 'pages/show' => 'projects#index'
  end

  get 'users/profile'

  get 'pages/_mylist'
  get 'pages/_favlist'
  get 'pages/_summary'
  get 'pages/logout'

  root 'pages#index'
  get 'pages/show'
  get 'pages/index'
  
  devise_for :users, path_names: { sign_in: "login", sign_out: "logout"} ,controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    registrations:'users/registrations'
  }









end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks , :dependent => :destroy
  belongs_to :user , :foreign_key => :user_id
  validates :title, presence: { message: "入力してください"}
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = current_user.projects.order(params[:sort])
    @projects.each do |project|
      if project.tasks.count.to_f == 0
        project.progress = -1
        project.save
      else
        project.progress = project.tasks.finished.count.to_f / project.tasks.count.to_f * 100
        project.save
      end
    end
  end

  def new
    @project = Project.new
  end

  def show
    @tasks = @project.tasks.order(params[:sort])
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to projects_path
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def project_params
      params[:project].permit(:title,:user_id)
  end

  def set_project
    @project = current_user.projects.find(params[:id])
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb

<%= simple_form_for @project,wrapper: "horizontal_form" do |f| %>

    <%= f.input :title , input_wrapper_html: { class: "col-xs-5" } %> <br>
    <%= f.hidden_field :user_id, value: current_user.id %><br>

    <%= f.button :submit %> <br>

<% end %>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<h1>Edit</h1>

<%= render 'projects/form' %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<% if @projects.count == 0 %>
  <h3>Let's create projects!</h3>
<% end %>
<table class="table table-striped table-bordered table-hover table-condensed">
  <thead>
    <tr>
      <th class="col-xs-4 col-ms-4 col-md-4 col-lg-4 center"><%= link_to "Project Name", :sort => "projects.title" %></th>
      <th class="col-xs-3 col-ms-3 col-md-3 col-lg-3 center"><%= link_to "Progress", :sort => "projects.progress" %></th>
      <th class="col-xs-3 col-ms-3 col-md-3 col-lg-3 center"><%= link_to "Created Time", :sort => "projects.created_at" %></th>
      <th class="col-xs-2 col-ms-2 col-md-2 col-lg-2 center">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr valign ="middle">
        <td><%= link_to project.title, project_path(project.id) %></td>
        <td>
          <% if project.tasks.count.to_f == 0 %>
            <%= "No Task" %>
          <% else %>
            <%= project.progress.round(1) %>%
          <% end %>
        </td>
        <td><%= project.created_at.in_time_zone("Asia/Tokyo").to_s(:published_on) %></td>
        <td align = "center">
          <%= link_to "Edit", edit_project_path(project.id), class: "btn btn-success btn-xs" %>
          <%= link_to "Delete", project_path(project.id),  method: :delete, data: {confirm: "are you sure?"}, class: "btn btn-danger btn-xs" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

  <%= link_to "Add New", new_project_path, class: "btn btn-default btn-lg" %>

app/views/projects/new.html.erb
<h1>Add project</h1>

<%= render 'projects/form' %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>

<%= link_to "Project一覧へ","/projects",class: "btn btn-default" %>

<table class="table table-striped table-bordered table-hover table-condensed">
  <thead>
    <tr>
      <th>Completion</th>      
      <th class="col-xs-4 col-ms-4 col-md-4 col-lg-4 center"><%= link_to "Task title", :sort => "tasks.title" %></th>
      <th class="col-xs-3 col-ms-3 col-md-3 col-lg-3 center"><%= link_to "Created time", :sort => "tasks.created_at" %></th>
      <th class="col-xs-3 col-ms-3 col-md-3 col-lg-3 center"><%= link_to "Due date", :sort => "tasks.due_date" %></th>
      <th class="col-xs-2 col-ms-2 col-md-2 col-lg-2 center">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td align = "center"><%= check_box_tag '', '', task.done, {'data-id' => task.id, 'data-project_id' => task.project_id} %></td>
        <td><%= task.title %></td>
        <td><%= task.created_at.in_time_zone("Asia/Tokyo").to_s(:published_on) %></td>
        <td><%= task.due_date.to_s(:due_date_on) %></td>
        <td align = "center"><%= link_to "Delete", project_task_path(task.project_id, task.id), method: :delete, data: {confirm: "are you sure?"} ,class: "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
    <%= simple_form_for [@project, @project.tasks.build],wrapper: "horizontal_form" do |f| %>
    <div class="form-group col-xs-12">
      <%= f.input :title,input_wrapper_html: { class: "col-xs-7 form-group-item" } %>
      <%= f.input :due_date, value: Date.today,input_wrapper_html: { class: "col-xs-4 form-group-item" } %>
    </div><br>

      <%= f.button :submit %>
    <% end %>
</div>

<script type="text/javascript">
    $(function() {
        $("input[type=checkbox]").click(function() {
            $.post('/projects/'+$(this).data('project_id')+'/tasks/'+$(this).data('id')+'/toggle')
        })
    })
</script>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>