config/routes.rb
Rails.application.routes.draw do
  
  resources :projects do
    resources :tasks, only: [:create, :destroy]
  end

  post '/projects/:project_id/tasks/:id/toggle' => 'tasks#toggle'

  get 'projects/index'

  get 'projects/new'

  get 'projects/show'

  get 'projects/create'

  get 'projects/edit'

  get 'projects/update'

  get 'projects/destroy'

  authenticated :user do
    get 'pages/show' => 'projects#index'
  end

  get 'users/profile'

  get 'pages/_mylist'
  get 'pages/_favlist'
  get 'pages/_summary'
  get 'pages/logout'

  root 'pages#index'
  get 'pages/show'
  get 'pages/index'
  
  devise_for :users, path_names: { sign_in: "login", sign_out: "logout"} ,controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    registrations:'users/registrations'
  }









end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks , :dependent => :destroy
  belongs_to :user , :foreign_key => :user_id
  validates :title, presence: { message: "入力してください"}
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project 
  validates :title,:due_date,
      presence: true

  scope :finished, -> { where(done: true) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:twitter]

         validates :username, presence: true, uniqueness: true

  has_many :projects , :dependent => :destroy

  

  def self.from_omniauth(auth)
    where(provider: auth["provider"], uid: auth["uid"]).first_or_create do |user|
      user.username = auth.info.nickname
      user.email = SecureRandom.uuid + "@example.com"
    end
  end
  
  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
        update_attributes(params, *options)
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def email_required?
    super && provider.blank?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 
  before_filter :configure_permitted_parameters, if: :devise_controller?
    def after_sign_in_path_for(resource)
      projects_path
    end

    def after_sign_out_path_for(resource)
      pages_logout_path
    end

    private
    
    def sign_in_required
        redirect_to new_user_session_url unless user_signed_in?
    end
 
  protected
 
    def configure_permitted_parameters
#      devise_parameter_sanitizer.for(:sign_in) << :username
      devise_parameter_sanitizer.for(:sign_up) << :username
      devise_parameter_sanitizer.for(:account_update) << :username
      devise_parameter_sanitizer.for(:sign_up) << :email
      devise_parameter_sanitizer.for(:account_update) << :email
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def new
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  def all
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = "ログインしました!!"
      user.skip_confirmation!
      sign_in_and_redirect user
    else
      session["devise.user_attributes"] = user.attributes
      flash.notice = "ログインしました!!"
      sign_in_and_redirect user
    end
  end
  alias_method :twitter, :all
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [:index,:logout]

  def index
  end

  def show
  end

  def _summary
  end

  def _favlist
  end

  def _mylist
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = current_user.projects.order(params[:sort])
    @projects.each do |project|
      if project.tasks.count.to_f == 0
        project.progress = -1
        project.save
      else
        project.progress = project.tasks.finished.count.to_f / project.tasks.count.to_f * 100
        project.save
      end
    end
  end

  def new
    @project = Project.new
  end

  def show
    @tasks = @project.tasks.order(params[:sort])
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to projects_path
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def project_params
      params[:project].permit(:title,:user_id)
  end

  def set_project
    @project = current_user.projects.find(params[:id])
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def create
    @project = Project.find(params[:project_id])
    @task    = @project.tasks.create(tasks_params)
    redirect_to project_path(@project.id)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to project_path(params[:project_id])
  end

  def toggle
      render nothing: true
      @task      = Task.find(params[:id])

      @task.done = !@task.done
      @task.save
  end

  private
    def tasks_params
      params[:task].permit(:title,:due_date)
    end

end

app/controllers/toppage_controller.rb
class ToppageController < ApplicationController
  def top
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
  end

  def login
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/toppage_helper.rb
module ToppageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Addminitter" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="contents">
      <div class="navbar navbar-default navbar-static-top ">

        <div class="container">

          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <% if user_signed_in? %>
            <a class="navbar-brand" href="/projects">Addminitter</a>
          <% else %>
            <a class="navbar-brand" href="/pages/index">Addminitter</a>
          <% end %>

          <div class="navbar-collapse collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %> 
                <li><%= link_to current_user.username, pages_show_path %></li>
                <li><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
                <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "サインイン", new_user_registration_path %></li>
                <li><%= link_to "ログイン", new_user_session_path %></li>
                <li><%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %></li>
              <% end %>
            </ul>
          </div>

        </div>

      </div>

      <div class="container wrap">

          <div>
            <%= bootstrap_flash %>
            <%= yield %>
          </div>

<!--
          <div class="col-lg-3">
            <ul class="list-group">
              <li class="list-group-item"><%= link_to'My Lists', "/pages/_mylist" %></li>
              <li class="list-group-item"><%= link_to'Favorite Lists', "/pages/_favlist" %></li>
              <li class="list-group-item"><%= link_to'Summary Page', "/pages/_summary" %></li>
            </ul>
          </div>
-->

      </div>
       
<!--
    <div class="footer">
      <footer class="container">
        <p>&copy; CirKit 2015</p>
      </footer>
    </div>
-->

  </body>
</html>

app/views/pages/_favlist.html.erb
<h1>Favorite list</h1>
<p>他人が作ったリストが表示されます。</p>

app/views/pages/_mylist.html.erb
<h1>Mylist</h1>
<p>自分が作ったリストが表示されます。</p>

app/views/pages/_summary.html.erb
<h1>Summary</h1>
<p>期限が近づいているカードを表示します。</p>

app/views/pages/index.html.erb
<h1>Welcome to AddMinitter!</h1>

app/views/pages/logout.html.erb
<h1>Thank you for using!</h1>

app/views/pages/show.html.erb
<h1>Hello,<%= current_user.username %>!</h1>
<div>
	<div class="well sidebar-nav col-lg-4 ">
		<%= render 'pages/mylist' %>
	</div>
	<div class="well sidebar-nav col-lg-4">
		<%= render 'pages/favlist' %>
	</div>
	<div class="well sidebar-nav col-lg-4">
		<%= render 'pages/summary' %>
	</div>
</div>